### PR TITLE
[Feature] Added a Details modal & Fixed Nested modal

### LINKED ISSUE #85: [Bug] Nested modal
The Login/Signin and Register/Signup modal(s) are nested.

They should be independent and tab indexed properly

### PR DESCRIPTION
**Pull request by Priyadharshini0101**
Resolves #85 #58 

- Separated Login and Signup modals (they are no longer nested).
- Added proper aria and tabindex attributes for accessibility.
- Created a Details modal that opens on clicking a “Details” button on a movie card.
- Displays detailed movie data
- Ensured links like IMDB/TMDB use accessible badges with proper aria-labels
- src is cleared when modal closes to stop playback

https://github.com/user-attachments/assets/88005f8d-3200-4e8d-95e5-6ffba88e3ca0

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
@Priyadharshini0101 

I checked out this change locally for review and testing for merge

Seems to work as the shared video describes.

Approving this PR for merge pending further review by collaborators

Thank you for the opportunity to review your PR and for your contributions.

File: Frontend/client/public/movies.mjs [hunk 1]
```diff
@@ -138,6 +137,37 @@ function createMovieCardHTML(movie) {
...
 
+window.showMovieDetails = function(movieId) {
+    const movieList = JSON.parse(localStorage.getItem("moviesList"));
+    const currentMovie = movieList.filter(m => m.id === Number(movieId));
+    if (!currentMovie) return;
+
+    const trailerUrl = currentMovie[0].trailerLink || "";
+    let embedUrl = "";
+    const videoId = trailerUrl.split("/").pop();
+    embedUrl = `https://www.youtube.com/embed/${videoId}`;
```
Comment (ZennilGreenherald) [inline Frontend/client/public/movies.mjs]: Can you define embedUrl where it's declared or vice versa?

Comment (Priyadharshini0101) [reply Frontend/client/public/movies.mjs]: @ZennilGreenherald  Hi, I have updated the changes. Please review

Comment (gbowne1) [reply Frontend/client/public/movies.mjs]: I usually prefer using the https://youtu.be/ share links but, embeds work fine.   It's quite possible that people will add them using the regular watch link `https://youtube.com/watch?v=` or a share link thats like `https://youtu.be/` but possibly also the `https://www.youtube.com/embed/`

Comment (Priyadharshini0101) [reply Frontend/client/public/movies.mjs]: Yes, I’ve updated the implementation to handle all the common YouTube link formats users might provide so that the correct video ID is extracted and embedded regardless of the input format.

**Review by gbowne1 — APPROVED** [review]
approving latest changes to this PR.

**Comment by itswael** [comment]
based on the video it looks like, the video in the modal keeps on playing even when the modal is closed.
@Priyadharshini0101 Could you please confirm if it is so?

**Comment by gbowne1** [comment]
@itswael have you synced / pulled lately? I didnt notice anything out of the ordinary.. except a mostly working feature.

**Comment by Priyadharshini0101** [comment]
@itswael I fixed that issue in this commit http://github.com/gbowne1/flickpicker/pull/87/commits/f1cd6286824c0fcc8fb47a151061ac941d42941d it is working fine 

https://github.com/user-attachments/assets/1d65901f-a2ce-4acf-9d83-f56e8cc32df6

**Review by itswael — APPROVED** [review]

**Comment by itswael** [comment]
@Priyadharshini0101 Thanks for the updated video, reviewed the code again and approved.

> @itswael have you synced / pulled lately? I didnt notice anything out of the ordinary.. except a mostly working feature.

it was in the video.
