### PR TITLE
Fix#17saving movies

### LINKED ISSUE #17: [Bug] Add Movie button feature doesn't work when saving movies
Clicking on the `Add Movie` button doesn't work, 

It just comes up with a dialog/modal that says failed to save movie and the URI/URL.

Fix this so it actually saves movies to the JSON file and or to the API, browser storage, db, etc. etc.

### PR DESCRIPTION
**Pull request by itswael**
fixed #17

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
@itswael 

I checked out this change locally for testing and review for merge.

I think this worked pretty well, but I will await another collaborator review as this is a pretty significant change.

I couldn't find much that didn't work after this, but this needs to be documented on how it works after merge. 

Thanks for your contribution and the opportunity to review your PR @itswael 

Approving this PR for merge.

File: Backend/routes.js [hunk 1]
```diff
@@ -1,9 +1,12 @@
 import express from 'express';
 import movieController from './controllers.js';
+import path from "path";
```
Comment (ZennilGreenherald) [inline Backend/routes.js:3]: Is path being used?

File: Frontend/client/public/index.html [hunk 2]
```diff
@@ -661,10 +661,20 @@ <h6 class="mt-3">Feedback</h6>
...
-        import { loadMovies } from '../public/loadMovies.mjs';
+        import { loadMovies } from './loadMovies.mjs';
     
         document.addEventListener('DOMContentLoaded', () => {
-            loadMovies(); // Dynamically loads and renders movies
+            loadMovies();
+        });
+
+        import { saveMovie } from './script.mjs';
+        document.addEventListener("DOMContentLoaded", () => {
```
Comment (ZennilGreenherald) [inline Frontend/client/public/index.html:671]: Should probably add { once: true } as the third param to all calls to document.addEventListener("DOMContentLoaded",...

Comment (ZennilGreenherald) [reply Frontend/client/public/index.html:671]: Why add these here in index.html?

Comment (gbowne1) [reply Frontend/client/public/index.html:671]: I agree with that.

File: Frontend/client/public/loadMovies.mjs [hunk 3]
```diff
@@ -163,7 +163,8 @@ async function loadFromCacheStorage() {
 // Load movies from JSON file served from localhost
 async function loadFromJson() {
     try {
-        const response = await fetch('http://localhost:3000/movieList.json');
+        console.log('Loading movies from JSON file...');
+        const response = await fetch('http://localhost:3000/movies');
```
Comment (ZennilGreenherald) [inline Frontend/client/public/loadMovies.mjs:167]: Should this avoid using the FQDN? maybe /movies or movies would be better?

File: Backend/routes.js (hunk 1 above)
Comment (gbowne1) [reply Backend/routes.js:3]: I think so. Let's see what settles in after this round.

File: Frontend/client/public/loadMovies.mjs (hunk 3 above)
Comment (gbowne1) [reply Frontend/client/public/loadMovies.mjs:167]: I don't know. It'll end up on a server. local is fine for dev till we get through working changes, yeah, /movies or something would work.

File: Frontend/client/public/index.html (hunk 2 above)
Comment (gbowne1) [reply Frontend/client/public/index.html:671]: I wasn't sure exactly what to do about saveMovie in script.mjs it normally should live with anything to do with movie CRUD, at least imho.

**Review by ZennilGreenherald — APPROVED** [review]
👍

File: Backend/routes.js (hunk 1 above)
Comment (rconjoe) [reply Backend/routes.js:3]: It's not being used here.

**Review by rconjoe — APPROVED** [review]

**Comment by gbowne1** [comment]
Marging this as is @itswael @rconjoe @ZennilGreenherald @iAmNsengi please sync/pull changes after merge thanks
